In [2]:
import pandas as pd
import numpy as np

In [3]:
df = pd.read_csv("full_dataset_v1.csv")
print(len(df))
df.head()

6011

,Unnamed: 0,date,OBJECTID,latitude,longitude,country,fatalities,injuries,type,trigger,...,event_im_1,latitude.1,longitude.1,country_co,admin_divi,gazetteer_,gazetteer1,submitted_,last_edite,slope
0,0,2008/11/03 00:00:00+00,3272,21.055900,105.829000,Vietnam,92,0,landslide,downpour,...,878,21.055900,105.829000,VN,Ha Noi,Hanoi,2.81,2014/04/01 00:00:00+00,2019/05/16 00:00:00+00,7
1,1,2008/09/25 00:00:00+00,7724,21.300000,106.623000,Vietnam,41,0,complex,tropical_cyclone,...,816,21.300000,106.623000,VN,Bac Giang,Nam Dien,4.70,2014/04/01 00:00:00+00,2019/05/16 00:00:00+00,34
2,2,2008/08/07 00:00:00+00,1214,22.266600,104.070000,Vietnam,37,0,complex,tropical_cyclone,...,696,22.266600,104.070000,VN,Lao Cai,Muong Bo,8.88,2014/04/01 00:00:00+00,2019/05/16 00:00:00+00,124
3,3,2017/10/12 00:00:00+00,872,20.652251,105.156024,Vietnam,18,0,landslide,downpour,...,,20.652251,105.156024,VN,Hoa Binh,Xom Lon,15.85,2018/08/15 00:00:00+00,2019/05/16 00:00:00+00,125
4,4,2011/04/01 00:00:00+00,6578,18.995400,105.462500,Vietnam,18,0,rock_fall,mining,...,3331,18.995400,105.462500,VN,Nghe An,Phuc Thanh,7.86,2014/09/11 00:00:00+00,2019/05/16 00:00:00+00,40

In [4]:
print(df.columns)

Index(['Unnamed: 0', 'date', 'OBJECTID', 'latitude', 'longitude', 'country',
       'fatalities', 'injuries', 'type', 'trigger', 'severity', 'location',
       'FID', 'source_nam', 'source_lin', 'event_time', 'event_id',
       'event_titl', 'event_desc', 'location_d', 'location_a', 'storm_name',
       'photo_link', 'comments', 'event_impo', 'event_im_1', 'latitude.1',
       'longitude.1', 'country_co', 'admin_divi', 'gazetteer_', 'gazetteer1',
       'submitted_', 'last_edite', 'slope'],
      dtype='object')